# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_test1_swig', [dirname(__file__)])
        except ImportError:
            import _test1_swig
            return _test1_swig
        if fp is not None:
            try:
                _mod = imp.load_module('_test1_swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _test1_swig = swig_import_helper()
    del swig_import_helper
else:
    import _test1_swig
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr



def high_res_timer_now():
  """high_res_timer_now() -> gr::high_res_timer_type"""
  return _test1_swig.high_res_timer_now()

def high_res_timer_now_perfmon():
  """high_res_timer_now_perfmon() -> gr::high_res_timer_type"""
  return _test1_swig.high_res_timer_now_perfmon()

def high_res_timer_tps():
  """high_res_timer_tps() -> gr::high_res_timer_type"""
  return _test1_swig.high_res_timer_tps()

def high_res_timer_epoch():
  """high_res_timer_epoch() -> gr::high_res_timer_type"""
  return _test1_swig.high_res_timer_epoch()
class toto(object):
    """Proxy of C++ gr::test1::toto class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make(*args, **kwargs):
        """make(int vlen, char const * filename, int repeat) -> toto_sptr"""
        return _test1_swig.toto_make(*args, **kwargs)

    make = staticmethod(make)
    __swig_destroy__ = _test1_swig.delete_toto
    __del__ = lambda self : None;
toto_swigregister = _test1_swig.toto_swigregister
toto_swigregister(toto)

def toto_make(*args, **kwargs):
  """toto_make(int vlen, char const * filename, int repeat) -> toto_sptr"""
  return _test1_swig.toto_make(*args, **kwargs)

class toto_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::test1::toto)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::test1::toto)> self) -> toto_sptr
        __init__(boost::shared_ptr<(gr::test1::toto)> self, toto p) -> toto_sptr
        """
        this = _test1_swig.new_toto_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(toto_sptr self) -> toto"""
        return _test1_swig.toto_sptr___deref__(self)

    __swig_destroy__ = _test1_swig.delete_toto_sptr
    __del__ = lambda self : None;
    def make(self, *args, **kwargs):
        """make(toto_sptr self, int vlen, char const * filename, int repeat) -> toto_sptr"""
        return _test1_swig.toto_sptr_make(self, *args, **kwargs)

    def history(self):
        """history(toto_sptr self) -> unsigned int"""
        return _test1_swig.toto_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(toto_sptr self, int which, int delay)
        declare_sample_delay(toto_sptr self, unsigned int delay)
        """
        return _test1_swig.toto_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(toto_sptr self, int which) -> unsigned int"""
        return _test1_swig.toto_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(toto_sptr self) -> int"""
        return _test1_swig.toto_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(toto_sptr self) -> double"""
        return _test1_swig.toto_sptr_relative_rate(self)

    def start(self):
        """start(toto_sptr self) -> bool"""
        return _test1_swig.toto_sptr_start(self)

    def stop(self):
        """stop(toto_sptr self) -> bool"""
        return _test1_swig.toto_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(toto_sptr self, unsigned int which_input) -> uint64_t"""
        return _test1_swig.toto_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(toto_sptr self, unsigned int which_output) -> uint64_t"""
        return _test1_swig.toto_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(toto_sptr self) -> int"""
        return _test1_swig.toto_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(toto_sptr self, int m)"""
        return _test1_swig.toto_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(toto_sptr self)"""
        return _test1_swig.toto_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(toto_sptr self) -> bool"""
        return _test1_swig.toto_sptr_is_set_max_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(toto_sptr self, int i) -> long"""
        return _test1_swig.toto_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(toto_sptr self, long max_output_buffer)
        set_max_output_buffer(toto_sptr self, int port, long max_output_buffer)
        """
        return _test1_swig.toto_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(toto_sptr self, int i) -> long"""
        return _test1_swig.toto_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(toto_sptr self, long min_output_buffer)
        set_min_output_buffer(toto_sptr self, int port, long min_output_buffer)
        """
        return _test1_swig.toto_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(toto_sptr self) -> float"""
        return _test1_swig.toto_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(toto_sptr self) -> float"""
        return _test1_swig.toto_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(toto_sptr self) -> float"""
        return _test1_swig.toto_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(toto_sptr self) -> float"""
        return _test1_swig.toto_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(toto_sptr self) -> float"""
        return _test1_swig.toto_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(toto_sptr self) -> float"""
        return _test1_swig.toto_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(toto_sptr self, int which) -> float
        pc_input_buffers_full(toto_sptr self) -> pmt_vector_float
        """
        return _test1_swig.toto_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(toto_sptr self, int which) -> float
        pc_input_buffers_full_avg(toto_sptr self) -> pmt_vector_float
        """
        return _test1_swig.toto_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(toto_sptr self, int which) -> float
        pc_input_buffers_full_var(toto_sptr self) -> pmt_vector_float
        """
        return _test1_swig.toto_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(toto_sptr self, int which) -> float
        pc_output_buffers_full(toto_sptr self) -> pmt_vector_float
        """
        return _test1_swig.toto_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(toto_sptr self, int which) -> float
        pc_output_buffers_full_avg(toto_sptr self) -> pmt_vector_float
        """
        return _test1_swig.toto_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(toto_sptr self, int which) -> float
        pc_output_buffers_full_var(toto_sptr self) -> pmt_vector_float
        """
        return _test1_swig.toto_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(toto_sptr self) -> float"""
        return _test1_swig.toto_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(toto_sptr self) -> float"""
        return _test1_swig.toto_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(toto_sptr self) -> float"""
        return _test1_swig.toto_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(toto_sptr self) -> float"""
        return _test1_swig.toto_sptr_pc_work_time_total(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(toto_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _test1_swig.toto_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(toto_sptr self)"""
        return _test1_swig.toto_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(toto_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _test1_swig.toto_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(toto_sptr self) -> int"""
        return _test1_swig.toto_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(toto_sptr self) -> int"""
        return _test1_swig.toto_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(toto_sptr self, int priority) -> int"""
        return _test1_swig.toto_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(toto_sptr self) -> std::string"""
        return _test1_swig.toto_sptr_name(self)

    def symbol_name(self):
        """symbol_name(toto_sptr self) -> std::string"""
        return _test1_swig.toto_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(toto_sptr self) -> io_signature_sptr"""
        return _test1_swig.toto_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(toto_sptr self) -> io_signature_sptr"""
        return _test1_swig.toto_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(toto_sptr self) -> long"""
        return _test1_swig.toto_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(toto_sptr self) -> basic_block_sptr"""
        return _test1_swig.toto_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(toto_sptr self, int ninputs, int noutputs) -> bool"""
        return _test1_swig.toto_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(toto_sptr self) -> std::string"""
        return _test1_swig.toto_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(toto_sptr self, std::string name)"""
        return _test1_swig.toto_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(toto_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _test1_swig.toto_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(toto_sptr self) -> swig_int_ptr"""
        return _test1_swig.toto_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(toto_sptr self) -> swig_int_ptr"""
        return _test1_swig.toto_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(toto_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _test1_swig.toto_sptr_message_subscribers(self, *args, **kwargs)

toto_sptr_swigregister = _test1_swig.toto_sptr_swigregister
toto_sptr_swigregister(toto_sptr)

toto_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
toto = toto.make;

class dds_fpga(object):
    """Proxy of C++ gr::test1::dds_fpga class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make(*args, **kwargs):
        """make(int nbSamp, std::string const & devname) -> dds_fpga_sptr"""
        return _test1_swig.dds_fpga_make(*args, **kwargs)

    make = staticmethod(make)
    __swig_destroy__ = _test1_swig.delete_dds_fpga
    __del__ = lambda self : None;
dds_fpga_swigregister = _test1_swig.dds_fpga_swigregister
dds_fpga_swigregister(dds_fpga)

def dds_fpga_make(*args, **kwargs):
  """dds_fpga_make(int nbSamp, std::string const & devname) -> dds_fpga_sptr"""
  return _test1_swig.dds_fpga_make(*args, **kwargs)

class dds_fpga_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::test1::dds_fpga)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::test1::dds_fpga)> self) -> dds_fpga_sptr
        __init__(boost::shared_ptr<(gr::test1::dds_fpga)> self, dds_fpga p) -> dds_fpga_sptr
        """
        this = _test1_swig.new_dds_fpga_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(dds_fpga_sptr self) -> dds_fpga"""
        return _test1_swig.dds_fpga_sptr___deref__(self)

    __swig_destroy__ = _test1_swig.delete_dds_fpga_sptr
    __del__ = lambda self : None;
    def make(self, *args, **kwargs):
        """make(dds_fpga_sptr self, int nbSamp, std::string const & devname) -> dds_fpga_sptr"""
        return _test1_swig.dds_fpga_sptr_make(self, *args, **kwargs)

    def history(self):
        """history(dds_fpga_sptr self) -> unsigned int"""
        return _test1_swig.dds_fpga_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(dds_fpga_sptr self, int which, int delay)
        declare_sample_delay(dds_fpga_sptr self, unsigned int delay)
        """
        return _test1_swig.dds_fpga_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(dds_fpga_sptr self, int which) -> unsigned int"""
        return _test1_swig.dds_fpga_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(dds_fpga_sptr self) -> int"""
        return _test1_swig.dds_fpga_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(dds_fpga_sptr self) -> double"""
        return _test1_swig.dds_fpga_sptr_relative_rate(self)

    def start(self):
        """start(dds_fpga_sptr self) -> bool"""
        return _test1_swig.dds_fpga_sptr_start(self)

    def stop(self):
        """stop(dds_fpga_sptr self) -> bool"""
        return _test1_swig.dds_fpga_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(dds_fpga_sptr self, unsigned int which_input) -> uint64_t"""
        return _test1_swig.dds_fpga_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(dds_fpga_sptr self, unsigned int which_output) -> uint64_t"""
        return _test1_swig.dds_fpga_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(dds_fpga_sptr self) -> int"""
        return _test1_swig.dds_fpga_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(dds_fpga_sptr self, int m)"""
        return _test1_swig.dds_fpga_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(dds_fpga_sptr self)"""
        return _test1_swig.dds_fpga_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(dds_fpga_sptr self) -> bool"""
        return _test1_swig.dds_fpga_sptr_is_set_max_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(dds_fpga_sptr self, int i) -> long"""
        return _test1_swig.dds_fpga_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(dds_fpga_sptr self, long max_output_buffer)
        set_max_output_buffer(dds_fpga_sptr self, int port, long max_output_buffer)
        """
        return _test1_swig.dds_fpga_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(dds_fpga_sptr self, int i) -> long"""
        return _test1_swig.dds_fpga_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(dds_fpga_sptr self, long min_output_buffer)
        set_min_output_buffer(dds_fpga_sptr self, int port, long min_output_buffer)
        """
        return _test1_swig.dds_fpga_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(dds_fpga_sptr self) -> float"""
        return _test1_swig.dds_fpga_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(dds_fpga_sptr self) -> float"""
        return _test1_swig.dds_fpga_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(dds_fpga_sptr self) -> float"""
        return _test1_swig.dds_fpga_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(dds_fpga_sptr self) -> float"""
        return _test1_swig.dds_fpga_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(dds_fpga_sptr self) -> float"""
        return _test1_swig.dds_fpga_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(dds_fpga_sptr self) -> float"""
        return _test1_swig.dds_fpga_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(dds_fpga_sptr self, int which) -> float
        pc_input_buffers_full(dds_fpga_sptr self) -> pmt_vector_float
        """
        return _test1_swig.dds_fpga_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(dds_fpga_sptr self, int which) -> float
        pc_input_buffers_full_avg(dds_fpga_sptr self) -> pmt_vector_float
        """
        return _test1_swig.dds_fpga_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(dds_fpga_sptr self, int which) -> float
        pc_input_buffers_full_var(dds_fpga_sptr self) -> pmt_vector_float
        """
        return _test1_swig.dds_fpga_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(dds_fpga_sptr self, int which) -> float
        pc_output_buffers_full(dds_fpga_sptr self) -> pmt_vector_float
        """
        return _test1_swig.dds_fpga_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(dds_fpga_sptr self, int which) -> float
        pc_output_buffers_full_avg(dds_fpga_sptr self) -> pmt_vector_float
        """
        return _test1_swig.dds_fpga_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(dds_fpga_sptr self, int which) -> float
        pc_output_buffers_full_var(dds_fpga_sptr self) -> pmt_vector_float
        """
        return _test1_swig.dds_fpga_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(dds_fpga_sptr self) -> float"""
        return _test1_swig.dds_fpga_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(dds_fpga_sptr self) -> float"""
        return _test1_swig.dds_fpga_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(dds_fpga_sptr self) -> float"""
        return _test1_swig.dds_fpga_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(dds_fpga_sptr self) -> float"""
        return _test1_swig.dds_fpga_sptr_pc_work_time_total(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(dds_fpga_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _test1_swig.dds_fpga_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(dds_fpga_sptr self)"""
        return _test1_swig.dds_fpga_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(dds_fpga_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _test1_swig.dds_fpga_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(dds_fpga_sptr self) -> int"""
        return _test1_swig.dds_fpga_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(dds_fpga_sptr self) -> int"""
        return _test1_swig.dds_fpga_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(dds_fpga_sptr self, int priority) -> int"""
        return _test1_swig.dds_fpga_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(dds_fpga_sptr self) -> std::string"""
        return _test1_swig.dds_fpga_sptr_name(self)

    def symbol_name(self):
        """symbol_name(dds_fpga_sptr self) -> std::string"""
        return _test1_swig.dds_fpga_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(dds_fpga_sptr self) -> io_signature_sptr"""
        return _test1_swig.dds_fpga_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(dds_fpga_sptr self) -> io_signature_sptr"""
        return _test1_swig.dds_fpga_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(dds_fpga_sptr self) -> long"""
        return _test1_swig.dds_fpga_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(dds_fpga_sptr self) -> basic_block_sptr"""
        return _test1_swig.dds_fpga_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(dds_fpga_sptr self, int ninputs, int noutputs) -> bool"""
        return _test1_swig.dds_fpga_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(dds_fpga_sptr self) -> std::string"""
        return _test1_swig.dds_fpga_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(dds_fpga_sptr self, std::string name)"""
        return _test1_swig.dds_fpga_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(dds_fpga_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _test1_swig.dds_fpga_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(dds_fpga_sptr self) -> swig_int_ptr"""
        return _test1_swig.dds_fpga_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(dds_fpga_sptr self) -> swig_int_ptr"""
        return _test1_swig.dds_fpga_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(dds_fpga_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _test1_swig.dds_fpga_sptr_message_subscribers(self, *args, **kwargs)

dds_fpga_sptr_swigregister = _test1_swig.dds_fpga_sptr_swigregister
dds_fpga_sptr_swigregister(dds_fpga_sptr)

dds_fpga_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
dds_fpga = dds_fpga.make;



